### ISSUE TITLE
Could not serialize

### ISSUE THREAD

**Issue by rovacado** [OverlordsIII/VillagerNames#1]
I receive this error on the server side:
[06:51:36] [Netty Epoll Server IO #2/ERROR]: Could not serialize io.github.overlordsiii.villagernames.command.argument.FormattingArgumentType@2d29f806 (class io.github.overlordsiii.villagernames.command.argument.FormattingArgumentType) - will not be sent to client!

along with this on the clientside:
[06:51:35] [Netty Client IO #1/ERROR]: Could not deserialize minecraft:
[06:51:35] [Netty Client IO #1/ERROR]: Could not deserialize inecraft:resource_locationminecraft:ask_server
![Screenshot 2020-11-04 065501](https://user-images.githubusercontent.com/23286860/98108892-b4959280-1e6a-11eb-8a67-7e28d04f7e69.png)

ninja edit:
I get this with all 3 versions on curseforge. also weirdly, after removing the mod and restarting the server, the villagers are in fact, named. This is all on 1.16.3 with latest fabric loader and api

**Comment by OverlordsIII** [comment]
I sort of half fixed it, but now you need the mod on the client as well as server to connect successfully
This is still a problem however, so I am still working on it

**Comment by OverlordsIII** [comment]
> ninja edit:
> I get this with all 3 versions on curseforge. also weirdly, after removing the mod and restarting the server, the villagers are in fact, named. This is all on 1.16.3 with latest fabric loader and api

as for this, the mod cant actually remove the villagers names after the mod is uninstalled, since naming mobs in minecraft is still a vanilla feature.

**Comment by OverlordsIII** [comment]
Try getting the latest release and see if it solves your problem

**Comment by rovacado** [comment]
> 
> 
> Try getting the latest release and see if it solves your problem

the patch fixed the problem up, no errors that i can find in the log, and spawning a few villages assigned names to them

**Comment by OverlordsIII** [comment]
Ok that is good to know. In the future the mod should also be server-side only eventually as well. So i'll just close this for now, and when its fixed i'll update here
