### ISSUE TITLE
Crash on village generation?

### ISSUE THREAD

**Issue by AzureMonument** [OverlordsIII/VillagerNames#13]
I've uploaded the crash log below. Don't know quite what is going on, but I saw this mod name in the crash a bunch so...

[crash-2020-12-28_12.16.31-server.txt](https://github.com/OverlordsIII/VillagerNames/files/5748222/crash-2020-12-28_12.16.31-server.txt)

**Comment by OverlordsIII** [comment]
I have uploaded a potential fix on curseforge, try to get the latest release and see if it works out.
