### ISSUE TITLE
Add compatibility with Requirem.

### ISSUE THREAD

**Issue by RDKRACZ** [OverlordsIII/VillagerNames#15]
![image](https://user-images.githubusercontent.com/43277609/103456317-3bdd7600-4cf5-11eb-9396-723f9a9a3af1.png)

When being a villager / iron golem the name is badly displayed in the gui.

**Comment by RDKRACZ** [comment]
I meant the name where the skin is shown, the one on the left.

**Comment by RDKRACZ** [comment]
The one on the right is not so easy to fix I guess.

**Comment by OverlordsIII** [comment]
This mod cannot really fix this because it is a server side only mod atm.
