### ISSUE TITLE
[Feature request] Village names.

### ISSUE THREAD

**Issue by RDKRACZ** [OverlordsIII/VillagerNames#18]
I would like to request names for villages like in this, not updated anymore, mod - https://youtu.be/3-RhR6XxMyY

**Comment by OverlordsIII** [comment]
Unfortunately I think this is out of scope for this mod, as it is only intended to give names to villagers themselves. By giving villages names, it implies that the mod is expanding/revamping villages in general which is false. In the future this should probably be done by a bigger villager mod.
