### ISSUE TITLE
Villagers are sometimes named "Forename the"

### ISSUE THREAD

**Issue by Fourmisain** [OverlordsIII/VillagerNames#19]
`professionNames`, `childNames` and `surNames` were all set to true.

I think I found how to reproduce the issue.

Start with 2 villagers with professions like such:
![2021-03-13](https://user-images.githubusercontent.com/8464472/111019969-e2638880-83c2-11eb-9214-f0e1733468ec.png)
Breed them.
Their child won't have a surname (which is already an issue I believe?) and will also have the profession text of their parent - which I'm not sure if intended. Is it?
![2021-03-13](https://user-images.githubusercontent.com/8464472/111019972-e4c5e280-83c2-11eb-8056-57d47c15889d.png)
When such a child grows up, it seems "the" is used as the surname
![2021-03-13](https://user-images.githubusercontent.com/8464472/111019728-61f05800-83c1-11eb-8c27-8083347a2715.png)
Though this apparently doesn't happen all the time?
![2021-03-13](https://user-images.githubusercontent.com/8464472/111019730-63218500-83c1-11eb-8141-94991aaaf536.png)

---

Ahhh!
I wrote a whole paragraph here about how I'm trying to rewrite the naming functions, maybe the way names are stored etc.

I just compiled the code of my prototype wanted to do some testing to get a (draft) pull request up - but I noticed that the code here on github is outdated, it's still on version 1.5.2, please fix!

**Comment by Fourmisain** [comment]
I just realized 1.6.0 is now pushed!

It's been so long since I wrote the rewrite that getting the PR done might take a while, if you want you can have a look at the (very unfinished) [code](https://github.com/Fourmisain/VillagerNames/commits/rewrite).

Initially I wanted to add separate fields for fore- and surnames, but I quickly gave up on that idea (commented it out) since it's not hard using the simple "Forename &lt;Surname> &lt;the Jobtitle>" scheme, where you first split at the potential " the " and then at the potential space.

I remember thinking of having names with spaces but also thinking about config options which could cause issues, like the one that switches fore- and surnames:
If you generate villagers one way, switch the setting, restart and generate new villagers, it becomes impossible to distinguish between fore- and surnames, which would (especially) be an issue when they could have spaces.
That would be something separate fields could solve, but then you also need to think about custom names from nametags - another field? "realNameTagName"?
Seemed like too much effort and too error-prone for what it's worth, so I kept the basics and simplified it as much as I could in the brief time till I realized I worked with an out-of-date version.

**Comment by MeeniMc** [comment]
Issue is still present in  2.0 for mc 1.17

**Comment by OverlordsIII** [comment]
Should be patched in latest version
