### ISSUE TITLE
Configuration issues

### ISSUE THREAD

**Issue by Meeni-mc** [OverlordsIII/VillagerNames#2]
This is fun! Thanks.

1. In the 'client' config (modmenu), the red text "/!\ any change requires a server restart" is offset to the left and is truncated at "ANY CH". (4k resolution, GUI size is 6)

2. In the 'server' config `villagername info` produces so much output that nothing is readable from the in-game chat, except the last entries of the "robot names" list. All other options are not visible because the chat has limited history. 

3. NEEDS OP should be TRUE by default (imo). It has no effect in single player games, and probably is always wanted "on" in multiplayer games.

**Comment by OverlordsIII** [comment]
Okay so basically
1. I'll fix this by probably just making so there is no offest at all
2. I'm not entirely sure what to do about this either than just not output the list for villagers and golems, and only output the rules for the mod instead
3. This is kind of clear i'll just set it too false 

Is this good? this will probably be done in next bug release

**Comment by Meeni-mc** [comment]
👍

**Comment by OverlordsIII** [comment]
Ok it's uploaded to curseforge, may take an hour or too to be reviewed. Try checking if it works after then.

**Comment by Meeni-mc** [comment]
All fixed in new version.
