### ISSUE TITLE
StringIndexOutOfBoundsException crash on villager breeding

### ISSUE THREAD

**Issue by Rx2TF** [OverlordsIII/VillagerNames#25]
Happened on v2.0.0
https://gist.githubusercontent.com/natanfudge/328c05852143ad47fad49ec3d3f21a0f/raw/b3af7db6039b76f22060783d5b2005f2251bb899/crash.txt

Also, the tooltip for Use Last Names is broken.

**Comment by OverlordsIII** [comment]
Should be fixed in latest version
