### ISSUE TITLE
Incompatibility with Charm

### ISSUE THREAD

**Issue by kekiev15** [OverlordsIII/VillagerNames#27]
Villagers generated by Charm (Woodcutters, and Beekeepers) generate their names as "NAME the charm_OCCUPATION" where NAME is a generated name and OCCUPATION is either woodcutter or beekeeper. Example, "John Smith the charm_woodcutter" or "Jane Doe the charm_beekeeper"

**Comment by YumatanGames** [comment]
We fixed this bug in the latest release. Unfortunately this will only solve the problem for newer villagers. For the old ones you'll need to replace their workstations. This should fix the problem if the villagers aren't locked in the profession. If they're locked, though, the only way to fix them is to rename them with nametags.
