### ISSUE TITLE
[Bug] child villager gets profession name as family name

### ISSUE THREAD

**Issue by leok77** [OverlordsIII/VillagerNames#29]
server game version: 1.18.1
fabricloader: 0.12.12
fabric api: 0.44.0+1.18
mod version: 2.0.2

In the first image, one child villager named "Ediltrudis the Fisherman", the reason is his parents are all "Fisherman". Perhaps when one of his parent is "Fisherman" will also get the same name like "XXX the Fisherman", I didn't test this. So I guess for this "Ediltrudis the Fisherman", "the Fisherman" is his family name he got from his parents, but unfortunately is used the profession name and with a "the" in front. And some child villagers get a name like "Linda the", which also shows in the first image.
In the second image, it shows a villager named "Lohrman the". And I think when he was a child, his name is "Lohrman the Fisherman" or just "Lohrman the".
In the third image, when these villagers get profession, the name becomes weird, like "Astride the the Toolsmith".

All the villagers borned by parents who had profession seems have this problem, they get "the profession" or "the" as their family name when they are children and "the" as their family name when grow up.

![child villager](https://user-images.githubusercontent.com/54049062/148885598-bc9c8ce3-95b4-47fa-89af-53ea3689db54.png)

![villager without profession](https://user-images.githubusercontent.com/54049062/148886456-fcd7a7f2-1835-4835-a105-bcb48fba80a5.png)

![villager with profession](https://user-images.githubusercontent.com/54049062/148886367-5995930f-6c03-4103-9d4e-b52c80da94c6.png)

**Comment by OverlordsIII** [comment]
Should be fixed in the [latest](https://www.curseforge.com/minecraft/mc-mods/villager-names-fabric/files/3655426) version, could you check to see if it works?

**Comment by leok77** [comment]
It works! Thanks!
