### ISSUE TITLE
Cannot properly set Golem names in config

### ISSUE THREAD

**Issue by mbrozzo** [OverlordsIII/VillagerNames#30]
I have created a custom list of names for villagers as well as golems. The villager config works fine, but in-game, the golem names list includes the default names on top of the ones I put in the config file. The config file only contains my custom names.

My golemNames.json:
```
{
  "golemNames": [
    "Robottino",
    "Automa",
    "Golem Ingranaggio Antico",
    "Robo-ceppo",
    "Burattino di Ferro",
    "Gesù 3",
    "Terachad",
    "Emiglio è Meglio"
  ]
}
```

In-game:
![image](https://user-images.githubusercontent.com/22538059/152342008-12204e22-4c53-4ef5-953a-7da42c285b68.png)

**Comment by OverlordsIII** [comment]
Sorry about this, it was a legacy piece of code to make sure users were up to date with their golem names. This will be fixed soon in the coming days

**Comment by mbrozzo** [comment]
Thank you!

**Comment by OverlordsIII** [comment]
This should be fixed, would you try seeing if the [latest ](https://www.curseforge.com/minecraft/mc-mods/villager-names-fabric/files/3655426)version of the mod fixes this issue? Should be version 3.0.0

**Comment by mbrozzo** [comment]
Thanks, I will try it and I will let you know!

**Comment by mbrozzo** [comment]
I tried version 3.0.0 on a clean install (with just dependencies and Mod Menu) and golem names seem to be working as expected, both in the config menu, both in-game.
Piglin names look like this instead (I had no config file for piglins, so an empty one was generated), si it normal?
![image](https://user-images.githubusercontent.com/22538059/154865877-7d7cd56a-2b84-4176-b7ee-de6a30834a41.png)

I could not find the file for version 3.0.0 on CurseForge though. I was able to download it only by updating the 2.0.2 file using GDLaucher, which in turn only shows version 3.0.0 for Minecraft 1.18.1. Is it just the CurseForge website which has not updated or is something going on?

**Comment by OverlordsIII** [comment]
We've found a major bug in version 3.0, so it has been archived. The piglin names looking like that is also very confusing, as it should look like the enchanting table text. Will be doing some more testing and debugging

**Comment by OverlordsIII** [comment]
The pillagers should be fixed now in [this](https://www.curseforge.com/minecraft/mc-mods/villager-names-fabric/files/3659772) version, could you check to see if it works on your side?

**Comment by mbrozzo** [comment]
Sure thing

**Comment by mbrozzo** [comment]
Wait, you meant piglins, right? In that case they seem to work as intended.

![image](https://user-images.githubusercontent.com/22538059/155582263-326e256c-45dc-4954-a97a-8ba93ecf9cb7.png)

**Comment by OverlordsIII** [comment]
My bad I get pillagers and piglins confused, but yes thats how they should look

**Comment by mbrozzo** [comment]
Thank you for the quick fix!
