### ISSUE TITLE
1.18.2 compatibility?

### ISSUE THREAD

**Issue by BrekiTomasson** [OverlordsIII/VillagerNames#33]
Any news on when we can expect compatibility with 1.18.2? Currently, loading the 1.18.1 version in 1.18.2 leads to an injector failure in `VillagerEntityMixin`

**Comment by OverlordsIII** [comment]
It should be fixed in the latest version [here](https://www.curseforge.com/minecraft/mc-mods/villager-names-fabric/files/3687440) along with a couple other features. Could you check it out and see if it works for you?

**Comment by BrekiTomasson** [comment]
Doesn't look like the upload has been made public by Curseforge yet, I'll check in tomorrow and let you know what I find.

**Comment by OverlordsIII** [comment]
Ah my bad I forgot CF takes a while to approve mods sometimes

**Comment by BrekiTomasson** [comment]
Initial tests done, seems like it's working as intended!

**Comment by OverlordsIII** [comment]
That's good to hear. I will close this issue for now but please let me know if you see any other issues in the future. Thanks for telling us about this!
