### ISSUE TITLE
[Compatibility Request] Name Guard Villagers

### ISSUE THREAD

**Issue by Wpgradford** [OverlordsIII/VillagerNames#34]
It would be a nice compatibility, as guard villagers are supposed to represent normal villagers who have the guard profession. I'm not sure if it's out of the scope of this mod, however, because I imagine it would require a good amount of work. Link to [Fabric Guard Villagers Curseforge page](https://www.curseforge.com/minecraft/mc-mods/guard-villagers-fabric)

**Comment by OverlordsIII** [comment]
[Here](https://www.curseforge.com/minecraft/mc-mods/villager-names-fabric/files/4215681)is a beta build that should add compatability for guard villagers.
