### ISSUE TITLE
1.18.2 Crash when curing Zombie Villager

### ISSUE THREAD

**Issue by milay** [OverlordsIII/VillagerNames#35]
Found a zombie villager in a cave near my spawner farm, trapped them in a boat, gave them a nametag ("Friend") so they don't respawn while I fetch the curing tools, came back with potion and apple and started the transformation.

When the curing was complete, I saw the zombie villager turn normal, only for the game to immediately freeze and crash. If I'm not mistaken, when checking the crash log, the Villager Names might have been the issue.

Crash log:

---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 4/9/22, 9:58 PM
Description: Ticking entity

java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at io.github.overlordsiii.villagernames.util.VillagerUtil.removeZombieVillagerName(VillagerUtil.java:191)
	at net.minecraft.class_1641.handler$fih000$returnOriginalVillagerName(class_1641.java:538)
	at net.minecraft.class_1641.method_7197(class_1641.java:241)
	at net.minecraft.class_1641.method_5773(class_1641.java:148)
	at net.minecraft.class_1297.method_5842(class_1297.java:1864)
	at net.minecraft.class_1309.method_5842(class_1309.java:2791)
	at net.minecraft.class_3218.method_18763(class_3218.java:725)
	at net.minecraft.class_3218.method_18762(class_3218.java:706)
	at net.minecraft.class_1937.method_18472(class_1937.java:485)
	at net.minecraft.class_3218.method_31420(class_3218.java:363)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:331)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:907)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851)
	at net.minecraft.class_1132.method_3748(class_1132.java:97)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
	at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at io.github.overlordsiii.villagernames.util.VillagerUtil.removeZombieVillagerName(VillagerUtil.java:191)
	at net.minecraft.class_1641.handler$fih000$returnOriginalVillagerName(class_1641.java:538)
	at net.minecraft.class_1641.method_7197(class_1641.java:241)
	at net.minecraft.class_1641.method_5773(class_1641.java:148)
	at net.minecraft.class_1297.method_5842(class_1297.java:1864)
	at net.minecraft.class_1309.method_5842(class_1309.java:2791)
	at net.minecraft.class_3218.method_18763(class_3218.java:725)
	at net.minecraft.class_3218.method_18762(class_3218.java:706)
	at net.minecraft.class_1937.method_18472(class_1937.java:485)
	at net.minecraft.class_3218.method_31420(class_3218.java:363)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:331)

-- Entity being ticked --
Details:
	Entity Type: minecraft:boat (net.minecraft.class_1690)
	Entity ID: 326316
	Entity Name: Boat
	Entity's Exact location: 79.31, -31.00, 114.86
	Entity's Block location: World: (79,-31,114), Section: (at 15,1,2 in 4,-2,7; chunk contains blocks 64,-64,112 to 79,319,127), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Entity's Momentum: 0.00, -0.00, 0.00
	Entity's Passengers: [class_1646['Uriqua Gittins the Enderian'/353002, l='ServerLevel[Paradise]', x=79.31, y=-31.55, z=114.86]]
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:485)
	at net.minecraft.class_3218.method_31420(class_3218.java:363)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:331)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:907)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851)
	at net.minecraft.class_1132.method_3748(class_1132.java:97)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Affected level --
Details:
	All players: 1 total; [class_3222['rootyful'/8326, l='ServerLevel[Paradise]', x=75.58, y=-31.13, z=113.32]]
	Chunk stats: 3879
	Level dimension: minecraft:overworld
	Level spawn location: World: (-32,118,32), Section: (at 0,6,0 in -2,7,2; chunk contains blocks -32,-64,32 to -17,319,47), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Level time: 7685695 game time, 10335912 day time
	Level name: Paradise
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
	Level weather: Rain time: 44153 (now: false), thunder time: 31468 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:907)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851)
	at net.minecraft.class_1132.method_3748(class_1132.java:97)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1401073552 bytes (1336 MiB) / 8506048512 bytes (8112 MiB) up to 9227468800 bytes (8800 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
	Identifier: Intel64 Family 6 Model 94 Stepping 3
	Microarchitecture: Skylake (Client)
	Frequency (GHz): 3.19
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: NVIDIA GeForce GTX 970
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x13c2
	Graphics card #0 versionInfo: DriverVersion=27.21.14.5671
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 29522.57
	Virtual memory used (MB): 23853.36
	Swap memory total (MB): 13182.95
	Swap memory used (MB): 1804.27
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8800m -Xms256m
	Fabric Mods: 
		additionaladditions: Additional Additions 3.0.1
		additionalbars: Additional Bars 3.0.0
		additionalstructures: Additional Structures 3.0.3
		adorn: Adorn 3.4.0+1.18.2
		advanced_runtime_resource_pack: Runtime Resource Pack 0.5.5
		advancements-enlarger: Advancements Enlarger 0.2.4
		advdebug: Advancements Debug 2.3.0
		adventurez: AdventureZ 1.4.10
		aqupdcaracal: Caracal mob 1.18.2-1.3.8
		aqupdgrizzly: Grizzly Bear mob 1.18-1.3
		architects_palette: Architect's Palette Fabric 1.7
		architectury: Architectury 4.1.39
		attributefix: AttributeFix 14.0.1
		autoconfig1u: Auto Config v1 Updated 3.4.0
		axolotlitemfix: Axolotl Item Fix 1.1.3
		balm-fabric: Balm 3.0.0+0
		basicshields: Basic Shields [Fabric] 1.3.1-1.18.2
		bcc: BetterCompatibilityChecker fabric-1.0.5
		beebetter: Bee Better 1.9.0-1.18.2
		beehivetooltips: Beehive Tooltips 1.4.2
		betteranimalsplus: Better Animals Plus 1.18.2-11.0.5
		betterdeserttemples: YUNG's Better Desert Temples 1.18.2-Fabric-1.0.0
		betterdungeons: YUNG's Better Dungeons 1.18.2-Fabric-2.0
		betterf3: BetterF3 1.2.4
		bettermineshafts: YUNG's Better Mineshafts 1.18.2-Fabric-2.0
		betterstrongholds: YUNG's Better Strongholds 1.18.2-Fabric-2.0
		betterthirdperson: Better Third Person 1.7.3
		bhmenu: BHMenu-Fabric 1.17.1-1.18.2-1.3
		biomeinfo: BiomeInfo 1.18.2-10
		biomemakeover: Biome Makeover 1.18.2-1.4.17
		blockus: Blockus 2.4.3+1.18.2
		blue_endless_jankson: jankson 1.2.1
		blur: Blur (Fabric) 2.4.1
		bookshelf: Bookshelf 13.0.10
		borderlessmining: Borderless Mining 1.1.1+1.18
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.3.6-1.18.2
		bowinfinityfix: Bow Infinity Fix rv11
		byg: Oh The Biomes You'll Go 1.4-RC-7
		capybara: Capybara 1.0.3
		cardinal-components: Cardinal Components API 4.1.4
		cardinal-components-base: Cardinal Components API (base) 4.1.4
		cardinal-components-block: Cardinal Components API (blocks) 4.1.4
		cardinal-components-chunk: Cardinal Components API (chunks) 4.1.4
		cardinal-components-entity: Cardinal Components API (entities) 4.1.4
		cardinal-components-item: Cardinal Components API (items) 4.1.4
		cardinal-components-level: Cardinal Components API (world saves) 4.1.4
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 4.1.4
		cardinal-components-world: Cardinal Components API (worlds) 4.1.4
		carrier: Carrier 1.10.0
		ce: Cave Enhancements 1.0.4
		cem: Custom Entity Models 0.7.1
		charm: Charm 4.0.0
		charmonium: Charmonium 4.0.0
		cherishedworlds: Cherished Worlds 2.0.1-1.18
		chunkcopy: Chunk Copy 2.0.0
		cleardespawn: Clear Despawn 1.1.7
		clearview: Lava Clear View 4.0.1
		clienttweaks: Client Tweaks 7.1.0
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-config: Cloth Config v6 6.2.57
		clumps: Clumps 8.0.0+7
		coat: Coat 1.0.0-beta.17+mc1.18.2
		collective-fabric: Collective (Fabric) 4.26
		com_electronwill_night-config_core: core 3.6.4
		com_electronwill_night-config_toml: toml 3.6.4
		com_eliotlash_mclib_mclib: mclib 18
		com_eliotlash_molang_molang: molang 18
		com_github_luben_zstd-jni: zstd-jni 1.5.2-2
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_typesafe_config: config 1.4.1
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		comforts: Comforts 1.1.2-1.18.2
		companion: Companion 2.0.0
		completeconfig: CompleteConfig 1.0.0
		consistency_plus: Consistency Plus 0.5.0-RC2+1.18.2
		continuity: Continuity 1.1.0+1.18.2
		controlling: Controlling For Fabric 9.0+17
		craftingtweaks: Crafting Tweaks 13.0.0
		crawl: Crawl 0.10.4
		creatures_of_the_jungle: Creatures From The Jungle 1.0.0
		creeperoverhaul: Creeper Overhaul 1.3.0
		croptopia: Croptopia 1.8.3
		crowdin-translate: CrowdinTranslate 1.4+1.18.2
		cullleaves: Cull Leaves 2.3.2
		damagetilt: Damage Tilt 1.18-fabric-0.1.2
		darkpaintings: DarkPaintings 10.0.1
		dashloader: DashLoader 3.1.1+1.18
		dawn: Dawn API 3.3.0
		decorative_blocks: Decorative Blocks 2.1.0
		deepslatecutting: Deepslate Cutting 1.3.2
		deleteworldstotrash: Delete Worlds To Trash 3.2.0
		dev_quantumfusion_dashloader_dashloader-core: dashloader-core 1.4.0
		dev_quantumfusion_hyphen: hyphen 0.2.0
		disenchanter: Disenchanter 0.1.5+1.18
		doublejump: Double Jump Mod 1.0.1+mc1.18
		dragonloot: DragonLoot 1.0.10
		drippyloadingscreen: Drippy Loading Screen 1.5.1
		duckling: Duckling 1.0.3
		dustrial_decor: Dustrial Decor 0.5
		dynamicfps: Dynamic FPS 2.1.0
		earthbounds: Earthbounds 1.0.5c
		earthtojavamobs: Earth2Java 1.8.0+1.18.2
		easymagic: Easy Magic 3.3.0
		easyshulkerboxes: Easy Shulker Boxes 3.1.1
		eatinganimationid: Eating Animation 1.5
		ecologics: Ecologics 1.5.2
		effective: Effective 1.2.1
		elytratrinket: Elytra Trinket 3.0.0-1.18.1
		enchantment_lore: Enchantment Lore 1.2.6-1
		enchdesc: EnchantmentDescriptions 10.0.2
		enhanced_attack_indicator: Enhanced Attack Indicator 1.0.3+1.18
		enhancedblockentities: Enhanced Block Entities 0.6+1.18.2
		entityculling: EntityCulling-Fabric 1.5.0
		equipmentcompare: Equipment Compare 1.2.12
		extended_armor_bars: Extended Armor Bars 1.2.1
		fabric: Fabric API 0.48.0+1.18.2
		fabric-api-base: Fabric API Base 0.4.4+d7c144a860
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.7+d7c144a860
		fabric-biome-api-v1: Fabric Biome API (v1) 8.0.3+801ec85b60
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.12+3ac43d9560
		fabric-command-api-v1: Fabric Command API (v1) 1.1.9+d7c144a860
		fabric-commands-v0: Fabric Commands (v0) 0.2.8+b4f4f6cd60
		fabric-containers-v0: Fabric Containers (v0) 0.1.21+d7c144a860
		fabric-content-registries-v0: Fabric Content Registries (v0) 3.0.2+d82b939260
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.11+3ac43d9560
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.17+2540745460
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.8+d7c144a860
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.19+d7c144a860
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.13+d7c144a860
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
		fabric-item-api-v1: Fabric Item API (v1) 1.3.3+691a79b560
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.10+3ac43d9560
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.12+54e5b2ec60
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.10+b4f4f6cd60
		fabric-language-kotlin: Fabric Language Kotlin 1.7.1+kotlin.1.6.10
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.0.2+2540745460
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.11+d7c144a860
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.0.4+d1027f7d60
		fabric-models-v0: Fabric Models (v0) 0.3.6+d7c144a860
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.21+d882b91560
		fabric-networking-v0: Fabric Networking (v0) 0.3.8+b4f4f6cd60
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.0.3+40c91ec860
		fabric-particles-v1: Fabric Particles (v1) 0.2.12+526dc1ac60
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.8+0d9ab37260
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.13+d882b91560
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.17+d8c7b9ae60
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.11+b4f4f6cd60
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.7+d7c144a860
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.2+54e5b2ec60
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.13+b4f4f6cd60
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.7+54e5b2ec60
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.2+d1027f7d60
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.18+2de5574560
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.10+d882b91560
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.14+40c91ec860
		fabric-textures-v0: Fabric Textures (v0) 1.0.12+3ac43d9560
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.14+cca23f9360
		fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.0.0+40c91ec860
		fabricenchantments: Fabric Enchantments 0.7.2
		fabricloader: Fabric Loader 0.13.3
		fabricshieldlib: Fabric Shield Lib 1.5.3-1.18
		fake-player-api: Fake Player API 0.3.0
		fallingleaves: Falling Leaves 1.10.0+1.18.2
		fallingtree: FallingTree 3.4.2
		fancymenu: FancyMenu 2.6.4
		feature_nbt_deadlock_be_gone: Feature NBT Deadlock Be Gone - Fabric 2.0.0+1.18.2-rc1
		ferritecore: FerriteCore 4.2.0
		fiber: fiber 0.23.0-2
		floral_flair: Floral Flair 1.3.0
		forgeconfigapiport: Forge Config API Port 3.2.0
		forgottenrecipes: ForgottenRecipes 1.18.1-1.0.0
		friendsandfoes: Friends&Foes 1.3.4
		geckolib3: Geckolib 3.0.35
		geodes: More Geodes 1.3.1
		goblintraders: Goblin Traders 1.5.1
		goosik-config: goosik-config 0.2.0
		graveyard: The Graveyard 1.7
		guardvillagers: Guard Villagers Fabric 1.18.2-1.0.11
		highlighter: Highlighter 1.1.2
		horseinfo: Horse Info 0.4.1-1.18
		hoverpets: Hover Pets 0.3.2
		icarus: Icarus 1.10
		iceberg: Iceberg 1.0.38
		illagerexp: Illager Expansion 0.1.4
		immersive_weathering: Immersive Weathering 2.3.2
		impactfulweather: Biome Particle Weather 2.3.5
		incantationem: Incantationem 1.1.3+1.18.2
		incendium: Incendium + Seed Fix 5.0.3
		indium: Indium 1.0.2+mc1.18.2
		ingredient-extension-api: Ingredient Extension API 2.0.5
		inmis: Inmis 2.5.3-1.18.2
		inventoryhud: Inventory HUD + 3.4.2
		invmove: InvMove 0.6.2
		io_leangen_geantyref_geantyref: geantyref 1.3.11
		iris: Iris 1.2.2-build.32
		jankson: Jankson 4.0.0+j1.2.0
		java: OpenJDK 64-Bit Server VM 17
		kleeslabs: KleeSlabs 11.0.0
		konkrete: Konkrete 1.3.3
		krypton: Krypton 0.1.9
		lambdynlights: LambDynamicLights 2.1.0+1.17
		lazydfu: LazyDFU 0.1.2
		libgui: LibGui 5.1.0+1.18
		libninepatch: LibNinePatch 1.1.0
		lithium: Lithium 0.7.9
		llamarama: Llamarama 1.6.4
		lovely_snails: Lovely Snails 1.0.4+1.18
		maelstrom_library: Maelstrom Library 1.2.4-1.18.2
		magnumtorch: Magnum Torch 3.1.2
		mambience: MAmbience 5.0.0+1.18.2
		mavm: More Axolotl Variants Mod 1.0.7a
		maybe-data: Maybe data 1.2.1-1.18.2
		maybe-more-data: Maybe More Data 1.0.0-1.18.2
		mcwbridges: Macaw's Bridges 2.0.2
		mcwdoors: Macaw's Doors 1.0.6
		mcwfences: Macaw's Fences and Walls 1.0.0
		mcwlights: Macaw's Lights and Lamps 1.0.3
		mcwtrpdoors: Macaw's Trapdoors 1.0.5
		mcwwindows: Macaw's Windows 2.0.3
		me_hypherionmc_simple-rpc-common: simple-rpc-common 1.0.20
		megaparrot: Megaparrot 1.0.4
		midnightlib: MidnightLib 0.4.0
		minecraft: Minecraft 1.18.2
		mm: Manningham Mills 2.3
		mob_catcher: Mob Catcher 1.1.26
		mobscarecrow: Mob Scarecrow 1.2.2
		modid: Creatures Of The Snow 1.0.0
		modmenu: Mod Menu 3.1.0
		more-axolotls: More Axolotls 1.0.2
		moreachievements: MoreAchievements 1.0.8
		morevillagers-fabric: MoreVillagersFabric 3.2.0-SNAPSHOT
		mousetweaks: Mouse Tweaks 2.22
		multipart_entities: MultipartEntities 1.1.5-1.18.2
		musicdr: Music Duration Reducer 2.0.0
		naturescompass: Nature's Compass 1.18.2-2.0.3-fabric
		nears: Nears 1.1.6
		notenoughanimations: NotEnoughAnimations 1.6.0
		omega-config: OmegaConfig 1.2.3-1.18.1
		onsoulfire: On Soul Fire 1.18-1
		orcinus: Hedgehog 1.18.2-1.0.1
		org_anarres_jcpp: jcpp 1.4.14
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.10
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.1
		org_joml_joml: joml 1.10.2
		org_json_json: json 20211205
		org_spongepowered_configurate-core: configurate-core 4.1.2
		org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		overweight_farming: Overweight Farming 1.18.2-1.1.0-fabric
		oxidized: Oxidized 1.6.3
		patchouli: Patchouli 1.18.2-66-FABRIC
		paxi: Paxi 1.18.2-Fabric-2.0
		phosphor: Phosphor 0.8.1
		pickupnotifier: Pick Up Notifier 3.2.0
		pickyourpoison: Pick Your Poison 1.0.4
		pigsteel: Pigsteel Mod 1.7.1
		placeholder-api: Placeholder API 1.1.3+1.17.1
		player-data-api: Player Data API 0.1.0+1.18
		plushies: Plushie Mod 1.2
		polymorph: Polymorph 0.0.20-1.18.2
		pride: Pride Lib 1.1.0+1.17
		puzzle: Puzzle 1.2.1
		puzzle-base: Puzzle Base 1.2.1
		puzzle-gui: Puzzle GUI 1.2.1
		puzzle-models: Puzzle Models 1.2.1
		puzzle-splashscreen: Puzzle Splash Screen 1.2.1
		puzzleslib: Puzzles Lib 3.3.1
		quartzelv: Quartz Elevator 2.1.1+1.18
		repurposed_structures: Repurposed Structures 4.1.1+1.18.2
		rightclickharvest: Right Click Harvest 1.5.1
		roughlyenoughitems: Roughly Enough Items 8.0.442
		roughlyenoughprofessions: Roughly Enough Professions 1.0.0
		runelic: Runelic 11.0.1
		satin: Satin 1.7.2
		sbm-jukebox: SBM-Jukebox 1.0.2
		seedfix: Seed Fix 1.0.2
		sentimentality3: Sentimentality 3 1.4.12
		simple-rpc: Simple Rpc 2.7.3
		skinlayers: 3d Skin Layers 1.4.2-mc1.18.2
		skylorlib: SkyLib 1.2.3
		slimyfloor: Slimy Floor 1.18.2-1.2.3
		snowballsfreezemobs-fabric: Snowballs Freeze Mobs (Fabric) 1.5
		sodium: Sodium 0.4.1+build.15
		sound_physics_remastered: Sound Physics Remastered 1.18.2-1.0.5
		spark: spark 1.8.14
		spirit: Spirit 1.2.1
		spruceui: SpruceUI 3.3.0+1.17
		starterkit-fabric: Starter Kit (Fabric) 3.1
		stonecutter_recipe_tags: Stonecutter Recipe Tags 3.0.1+1.18.bc850d5.fabric
		styled-nicknames: Styled Nicknames 1.0.4+1.18
		styledchat: Styled Chat 1.2.3+1.18
		stylisheffects: Stylish Effects 3.1.0
		terrablender: TerraBlender 1.1.0.99
		terraform-wood-api-v1: Terraform Wood API (v1) 3.0.0
		the_bumblezone: The Bumblezone - Fabric 5.0.10+1.18.2
		thonkutil: ThonkUtil 2.12.0+1.18
		thonkutil-base: ThonkUtil Base 1.12.0+93f5607360
		thonkutil-capes-v1: ThonkUtil Capes (v1) 1.3.1+974d16dd60
		thonkutil-coords-v1: ThonkUtil Coords (v1) 1.0.18+4c66479160
		thonkutil-customization-v1: ThonkUtil Customization (v1) 1.0.13+4c66479160
		thonkutil-legacy: ThonkUtil Legacy 1.0.19+aa74e18060
		thonkutil-modchecker-v1: ThonkUtil ModChecker (v1) 1.0.11+4c66479160
		thonkutil-potions-v0: ThonkUtil Potions (v0) 1.4.0+6d0d59d760
		thonkutil-titlescreen-v1: ThonkUtil TitleScreen (v1) 1.1.8+4c66479160
		thonkutil-trades-v1: ThonkUtil Trades (v1) 1.1.19+4c66479160
		tlcosmetica: Cosmetica 0.4.0
		toms_storage: Tom's Simple Storage Mod 1.3.0
		tradingpost: Trading Post 3.2.0
		travelerstitles: Traveler's Titles 1.18.2-Fabric-2.0
		trinketofundying: Trinket of Undying 2.0.1-1.18
		trinkets: Trinkets 3.3.0
		tweed4_annotated: tweed4_annotated 1.3.0
		tweed4_base: tweed4_base 1.5.0+mc1.18.2
		tweed4_data: tweed4_data 1.2.1+mc1.18.2
		tweed4_data_hjson: tweed4_data_hjson 1.1.0
		tweed4_tailor_coat: tweed4_tailor_coat 1.1.2+mc1.18.2
		tweed4_tailor_screen: tweed4_tailor_screen 1.1.1+mc1.18.2
		twigs: Twigs 1.1.3-patch1+1.18.2
		universal_ores: Universal Ores 1.2.1
		universalbonemeal: Universal Bone Meal 3.0.2
		vanilla_degus: Vanilla Degus 1.3.0
		veinmining: Vein Mining 0.0.12-1.18.2
		villager-hats: Villager Hats Mod 1.3.1
		villagernames: Villager Names 4.0.3
		visuality: Visuality 0.4.2
		visualworkbench: Visual Workbench 3.2.0
		voidtotem: VoidTotem (Fabric) 1.18.2-1.3.1
		voidz: VoidZ 1.0.6
		wandering_collector: Wandering Collector 1.1.2+mc1.18.2
		waterdripsound: Drip Sounds 1.18-0.3.0
		waystones: Waystones 2.5.0
		wildlife: Wildlife 1.18.2-1.0
		windchimes: Windchimes 1.2.0
		witherturnsskeletons: Wither turns Skeletons 1.2.0-1.18.2
		wmitaf: WMITAF 2.2.0
		wthit: wthit 4.8.1
		wunderreich: Wunderreich 1.0.0
		xaerominimap: Xaero's Minimap 22.4.0
		xaeroworldmap: Xaero's World Map 1.20.5
		yigd: You're in Grave Danger 1.3.1
		yungsapi: YUNG's API 1.18.2-Fabric-2.0.7
		yungsbridges: YUNG's Bridges 1.18.2-Fabric-2.0
		yungsextras: YUNG's Extras 1.18.2-Fabric-2.0
		zihlaunchpads: ZIHLaunchpads 1.2.0
	Loaded Shaderpack: ComplementaryShaders_v4.1.zip
		Profile: HIGH (+0 options changed by user)
	Server Running: true
	Player Count: 1 / 8; [class_3222['rootyful'/8326, l='ServerLevel[Paradise]', x=75.58, y=-31.13, z=113.32]]
	Data Packs: vanilla, Fabric Mods, file/VanillaTweaks_c996620.zip, file/armor statues v2.8.3.zip, file/cauldron concrete v2.0.5.zip, file/count mob deaths v1.1.2.zip, file/custom nether portals v2.3.5.zip, file/double shulker shells v1.3.2.zip, file/dragon drops v1.3.2.zip, file/durability ping v1.1.2.zip, file/more mob heads v2.9.4.zip, file/nether portal coords v1.1.2.zip, file/real time clock v1.1.2.zip, file/silence mobs v1.1.2.zip, file/track raw statistics v1.5.2.zip, file/track statistics v1.1.3.zip, file/unlock all recipes v2.0.3.zip, file/villager workstation highlights v1.1.2.zip, file/wandering trades v1.5.1.zip, file/Budding.Blocks.Silktouchable.zip, Repurposed_Structures-Friends_And_Foes-v1.zip, Repurposed_Structures-More_Villagers_v5.zip, file/Mambience-5.0.0+1.18.2-data.zip (incompatible)
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'

**Comment by OverlordsIII** [comment]
It should be fixed now, would you mind checking if it works for you on the latest version found [here](https://www.curseforge.com/minecraft/mc-mods/villager-names-fabric/files/3765309)? (Might take some time for Curseforge to approve though)
