### ISSUE TITLE
Spotted error in log.

### ISSUE THREAD

**Issue by coornio** [OverlordsIII/VillagerNames#39]
[main/ERROR]: Injection error: Invalid descriptor on villagernames.mixins.json:ZombieEntityMixin from mod villagernames->@Inject::addZombieNameTag(Lnet/minecraft/class_3218;Lnet/minecraft/class_1309;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Lnet/minecraft/class_1646;Lnet/minecraft/class_1641;)V! 

Expected (Lnet/minecraft/class_3218;Lnet/minecraft/class_1309;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Lnet/minecraft/class_1646;Lnet/minecraft/class_1641;)V 
but found (Lnet/minecraft/class_3218;Lnet/minecraft/class_1309;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Lnet/minecraft/class_1646;Lnet/minecraft/class_1641;)V

Not certain if this is important or not. The game (and mod) works fine, but I thought I should bring it to your attention.

**Comment by MrFaux** [comment]
For my server, it causes hardcrash.
