### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Demandro** [OverlordsIII/VillagerNames#4]
I had a crash, first things what I saw in crash-log were something/something/villagernames/something...
so I figured I should post it here:
---- Minecraft Crash Report -------- Minecraft Crash Report ----// I bet Cylons wouldn't have this problem.
Time: 20.7.11 21:23Description: Exception ticking world
java.lang.StringIndexOutOfBoundsException: String index out of range: -1 at java.lang.String.substring(String.java:1955) at io.github.overlordsiii.villagernames.util.VillagerUtil.generalVillagerUpdate(VillagerUtil.java:145) at io.github.overlordsiii.villagernames.VillagerNames.lambda$onInitialize$1(VillagerNames.java:42) at io.github.overlordsiii.villagernames.VillagerNames$$Lambda$2304/550719857.onLoad(Unknown Source) at net.minecraft.class_3218.handler$zld000$onLoadEntity(class_3218.java:2580) at net.minecraft.class_3218.method_18778(class_3218.java:938) at net.minecraft.class_3218.method_18214(class_3218.java:846) at net.minecraft.class_3898.method_17227(class_3898.java:635) at net.minecraft.class_3898$$Lambda$5268/112880050.apply(Unknown Source) at com.mojang.datafixers.util.Either.lambda$mapLeft$0(Either.java:162) at com.mojang.datafixers.util.Either$$Lambda$5269/1822301351.apply(Unknown Source) at com.mojang.datafixers.util.Either$Left.map(Either.java:38) at com.mojang.datafixers.util.Either.mapLeft(Either.java:162) at net.minecraft.class_3898.method_20460(class_3898.java:611) at net.minecraft.class_3898$$Lambda$5265/1632723945.apply(Unknown Source) at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602) at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577) at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) at net.minecraft.class_3900.method_17634(class_3900.java:58) at net.minecraft.class_3900$$Lambda$5163/1940363730.run(Unknown Source) at net.minecraft.class_1255.method_18859(class_1255.java:144) at net.minecraft.class_3215$class_4212.method_18859(class_3215.java:545) at net.minecraft.class_1255.method_16075(class_1255.java:118) at net.minecraft.class_3215$class_4212.method_16075(class_3215.java:554) at net.minecraft.class_3215.method_19492(class_3215.java:280) at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:749) at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:737) at net.minecraft.class_1255.method_5383(class_1255.java:103) at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:721) at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:674) at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) at net.minecraft.server.MinecraftServer$$Lambda$5043/197190171.run(Unknown Source) at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:---------------------------------------------------------------------------------------
-- Head --Thread: Server threadStacktrace: at java.lang.String.substring(String.java:1955) at io.github.overlordsiii.villagernames.util.VillagerUtil.generalVillagerUpdate(VillagerUtil.java:145) at io.github.overlordsiii.villagernames.VillagerNames.lambda$onInitialize$1(VillagerNames.java:42) at io.github.overlordsiii.villagernames.VillagerNames$$Lambda$2304/550719857.onLoad(Unknown Source) at net.minecraft.class_3218.handler$zld000$onLoadEntity(class_3218.java:2580) at net.minecraft.class_3218.method_18778(class_3218.java:938) at net.minecraft.class_3218.method_18214(class_3218.java:846) at net.minecraft.class_3898.method_17227(class_3898.java:635) at net.minecraft.class_3898$$Lambda$5268/112880050.apply(Unknown Source) at com.mojang.datafixers.util.Either.lambda$mapLeft$0(Either.java:162) at com.mojang.datafixers.util.Either$$Lambda$5269/1822301351.apply(Unknown Source) at com.mojang.datafixers.util.Either$Left.map(Either.java:38) at com.mojang.datafixers.util.Either.mapLeft(Either.java:162) at net.minecraft.class_3898.method_20460(class_3898.java:611) at net.minecraft.class_3898$$Lambda$5265/1632723945.apply(Unknown Source) at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602) at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577) at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) at net.minecraft.class_3900.method_17634(class_3900.java:58) at net.minecraft.class_3900$$Lambda$5163/1940363730.run(Unknown Source) at net.minecraft.class_1255.method_18859(class_1255.java:144) at net.minecraft.class_3215$class_4212.method_18859(class_3215.java:545) at net.minecraft.class_1255.method_16075(class_1255.java:118) at net.minecraft.class_3215$class_4212.method_16075(class_3215.java:554) at net.minecraft.class_3215.method_19492(class_3215.java:280) at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:749)
-- Affected level --Details: All players: 1 total; [class_3222['Demandro'/194, l='ServerLevel[Fabric Test]', x=-561.82, y=78.03, z=835.71]] Chunk stats: ServerChunkCache: 3007 Level dimension: minecraft:overworld Level spawn location: World: (192,73,256), Chunk: (at 0,4,0 in 12,16; contains blocks 192,0,256 to 207,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511) Level time: 18257 game time, 18257 day time Level name: Fabric Test Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true Level weather: Rain time: 29926 (now: false), thunder time: 16325 (now: false) Known server brands: fabric Level was modded: true Level storage version: 0x04ABD - AnvilStacktrace: at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:874) at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811) at net.minecraft.class_1132.method_3748(class_1132.java:91) at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670) at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) at net.minecraft.server.MinecraftServer$$Lambda$5043/197190171.run(Unknown Source) at java.lang.Thread.run(Thread.java:745)
-- System Details --Details: Minecraft Version: 1.16.4 Minecraft Version ID: 1.16.4 Operating System: Windows 10 (amd64) version 10.0 Java Version: 1.8.0_51, Oracle Corporation Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation Memory: 775240752 bytes (739 MB) / 1744830464 bytes (1664 MB) up to 2147483648 bytes (2048 MB) CPUs: 4 JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M Fabric Mods:  advanced_runtime_resource_pack: Runtime Resource Pack 0.2.6 advancednbttooltip: Advanced NBT Tooltips 1.0.6+build.2-1.16.4 amecsapi: Amecs API 1.1.1+mc1.16-rc1 autoconfig1u: Auto Config v1 Updated 3.3.1 backslot: BackSlot 1.1.7 bouncylife: Bouncy Life 1.1.8+mc1.16.4 camp_fires_cook_mobs: Camp Fires Cook Mobs 1.1.5+MC1.16.2-1.16.4 cardinal-components-base: Cardinal Components API (base) 2.7.2 cardinal-components-entity: Cardinal Components API (entities) 2.7.2 cardinal-components-world: Cardinal Components API (worlds) 2.7.2 cauldronoverhaul: Cauldron Overhaul 1.5.0 cloth-basic-math: Cloth Basic Math 0.5.1 cloth-client-events-v0: Cloth Client Events v0 1.4.5 cloth-config2: Cloth Config v4 4.8.3 cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.2.1 commonformatting: common formatting 0.0.0 craftpresence: CraftPresence 1.7.2 crawl: Crawl 0.7.5 crumbs: Crumbs 1.0.1+1.16.3-fabric dynamicentry: dynamic entry 0.1.3 extraalchemy: Extra Alchemy 1.3.0 fabric: Fabric API 0.25.1+build.416-1.16 fabric-api-base: Fabric API Base 0.2.0+9f0fb4b83a fabric-biome-api-v1: Fabric Biome API (v1) 3.0.0+8367596d3a fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea893a fabric-command-api-v1: Fabric Command API (v1) 1.0.9+a4467d2a3a fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d308363a fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f3a fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea8663a fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d3a fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+f8ac1db23a fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b3a fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.3+a4467d2a3a fabric-item-api-v1: Fabric Item API (v1) 1.2.0+f8ac1db23a fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.1+a4467d2a3a fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c63a fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c53a fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+74cc3b203a fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+432ea1883a fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce993a fabric-models-v0: Fabric Models (v0) 0.1.1+f8ac1db23a fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b3a fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f3a fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.2+a89534ab3a fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.1+a4467d2a3a fabric-particles-v1: fabric-particles-v1 0.2.2+fb0d9b0e3a fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.6.1+a4467d2a3a fabric-renderer-api-v1: Fabric Renderer API (v1) 0.3.3+a4467d2a3a fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.3+a4467d2a3a fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.0+f8ac1db23a fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+f8ac1db23a fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.12+f8ac1db23a fabric-rendering-v0: Fabric Rendering (v0) 1.1.1+f8ac1db23a fabric-rendering-v1: Fabric Rendering (v1) 1.3.1+f8ac1db23a fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.3.1+facf3bbf3a fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+872498413a fabric-structure-api-v1: Fabric Structure API (v1) 1.1.0+f8ac1db23a fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.0.4+3e817a6222 fabric-textures-v0: Fabric Textures (v0) 1.0.5+a4467d2a3a fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.4+2b4623793a fabricasmtools: Fabric ASM tools 0.3.1 fabricloader: Fabric Loader 0.10.6+build.214 falling_tree: FallingTree 2.5.1 fatxporbs: Fat Experience Orbs 0.0.7 greater_eye: Greater Eye of Ender 1.1.3 grindenchantments: Grind Enchantments 1.1.3+1.16.3 grossfabrichacks: GrossFabricHacks 0.8.3 lambdynlights: LambDynamicLights 1.3.2+1.16.4 leaf-decay: Leaf Decay 1.2.0-1.16.1 limitless: limitless 0.7.3 minecraft: Minecraft 1.16.4 mm: Manningham Mills 2.1 modmenu: Mod Menu 1.14.6+build.31 net_bytebuddy_byte-buddy-agent: byte-buddy-agent 1.10.18 net_gudenau_lib_unsafe: unsafe 1.3.4 netherite_plus: Netherite Plus Mod 1.1.0 noexpensive: NoExpensive 1.16.4-Fabric-1.1.4 notchify: Notchify 0.3.0 onsoulfire: On Soul Fire 1.16.4-1 pandemonium: Requiem: Pandemonium 1.2.2 pandemoniumapi: Requiem: Pandemonium-API 1.2.2 phormat: phormat 0.1.3 playerabilitylib: Pal 1.2.1 rare-ice: Rare Ice 0.2.2 requiem: Requiem 1.2.2 requiemapi: Requiem-API 1.2.2 roughlyenoughitems: Roughly Enough Items 5.7.1 roughlyenoughitems-api: REI (API) 5.7.1 roughlyenoughitems-default-plugin: REI (Default Plugin) 5.7.1 roughlyenoughitems-runtime: REI (Runtime) 5.7.1 satin: Satin 1.5.1 sheepconsistency: Sheep Consistency 1.0.2 sit: Sit 1.16.2-9 spruceui: SpruceUI 1.6.4 tweed: Tweed API 3.0.0-beta.15 user11681_reflect: reflect 0.13.4 villagernames: Villager Names 1.2.2 wi_zoom: WI Zoom 1.2-MC1.16.4 Player Count: 1 / 8; [class_3222['Demandro'/194, l='ServerLevel[Fabric Test]', x=-561.82, y=78.03, z=835.71]] Data Packs: vanilla (incompatible), fabric/netherite_plus, fabric/greater_eye, fabric/fabric-tool-attribute-api-v1, fabric/rare-ice (incompatible), fabric/extraalchemy, fabric/requiem (incompatible), fabric/crumbs, fabric/limitless, fabric/bouncylife, fabric/pandemonium Type: Integrated Server (map_client.txt) Is Modded: Definitely; Client brand changed to 'fabric'

**Comment by OverlordsIII** [comment]
Ok thanks for submitting a bug report. Was this happening when you first installed the mod and entered your world?

**Comment by OverlordsIII** [comment]
ok sorry about the late response, but it should be all good now. Try to get the latest release on curseforge and try it out

**Comment by OverlordsIII** [comment]
I'm going to go ahead and close this, try getting the latest release and if the problem keeps occurring, reopen the issue
