### ISSUE TITLE
Incompatible with Fabric Carpet 1.4.91

### ISSUE THREAD

**Issue by spencer-n1** [OverlordsIII/VillagerNames#49]
game wont start, just says Exit Code 1. playing on 1.19.2 tested with fabric api 0.68.0, fabric carpet 1.4.91, and villager names 4.0.8

**Comment by OverlordsIII** [comment]
Should be fixed now, check the file [here](https://www.curseforge.com/minecraft/mc-mods/villager-names-fabric/files/4215700) (might take some time for curseforge to approve)
