### ISSUE TITLE
Villager names causes rejection of clients

### ISSUE THREAD

**Issue by tacogerbil** [OverlordsIII/VillagerNames#7]
Been trying to set up a bungeecord/velocity environment and have hit a wall where according to the devs for Velocity and Crossstitch (after looking at the source code) there is a best practice standard proper namespace key and it is not implemented in Villager Names.  This causes Crossstitch to fail at trying to handle the VillagerNames mod.. 
It rejects with the error
disconnected with: DecoderException : java.lang.IllegalArgumentException: No provider for argument minecraft:golemname @ io.netty.handler.codec.MessageToMessageDecoder:98

**Comment by OverlordsIII** [comment]
Should be fixed with the latest pull request, I will release a new release for it soon

**Comment by OverlordsIII** [comment]
Okay just published it to curseforge, try to get the latest release. Sorry about the late response, I had a couple of other things I was working on the mod

**Comment by OverlordsIII** [comment]
I am going to go ahead and close this. if you haven't gotten the latest release, try getting it and if the issue persists, reopen the issue
